version: 2
updates:
  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Thomasxxl02"
    assignees:
      - "Thomasxxl02"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore(deps):"
      prefix-development: "chore(deps-dev):"
      include: "scope"
    allow:
      - dependency-type: "all"
    rebase-strategy: "auto"
    pull-request-branch-name:
      separator: "/"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:30"
    reviewers:
      - "Thomasxxl02"
    labels:
      - "ci/cd"
      - "github-actions"
    commit-message:
      prefix: "ci:"
      include: "scope"
