# This file lets you advertise supported ways for people to financially support your project

# Use a maximum of 4 options to fund open source projects
patreon: thomasxxl02
# github: []
# open_collective:
# ko_fi:
# buy_me_a_coffee:
# liberapay:
# issuehunt:
# polar:
# custom: []
